AWSTemplateFormatVersion: "2010-09-09"


Parameters:
  MyKeyName:
    Type: AWS::EC2::KeyPair::KeyName
 

  MyBucketName:
    Default: ismaeels3bucketfornestedstack3
    Type: String    



  VpcCIDR:
    Default: 10.0.0.0/16
    Description: ip range (CIDR notation) for this VPC
    Type: String

  PublicSubnet1CIDR:
    Default: 10.0.1.0/24
    Description: ip range (CIDR notation) for this VPC
    Type: String

  PublicSubnet2CIDR:
    Default: 10.0.3.0/24
    Description: ip range (CIDR notation) for this VPC
    Type: String

  PrivateSubnet1CIDR:
    Default: 10.0.2.0/24
    Description: ip range (CIDR notation) for this VPC
    Type: String
  PrivateSubnet2CIDR:
    Default: 10.0.4.0/24
    Description: ip range (CIDR notation) for this VPC
    Type: String
  ImageId:
    Type: String
    Default: ami-0d5eff06f840b45e9
    

  InstanceType:
    Type: String
    Default: t2.micro






Resources:
  MyVPCStack:           
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${MyBucketName}.s3.us-east-1.amazonaws.com/VPCIsmaeelconfig.yml
      Parameters:  
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR

 
  

  SecurityGroupStack:  
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${MyBucketName}.s3.us-east-1.amazonaws.com/securitygroup.yml
      Parameters:
          VPCId: !GetAtt MyVPCStack.Outputs.VpcId       





        
  DatabaseBstack:  
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${MyBucketName}.s3.us-east-1.amazonaws.com/RDSInstance.yml
      Parameters:
        vpcID: !GetAtt MyVPCStack.Outputs.VpcId
        DBprivateSubnet1: !GetAtt MyVPCStack.Outputs.PrivateSubnet1
        DBprivateSubnet2: !GetAtt MyVPCStack.Outputs.PrivateSubnet2
        webserverSGID: !GetAtt SecurityGroupStack.Outputs.group1ID







  ApplicatonLoadbalancerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${MyBucketName}.s3.us-east-1.amazonaws.com/loadbalancer.yml
      Parameters:
        VpcId: !GetAtt MyVPCStack.Outputs.VpcId
        PublicSubnet1: !GetAtt MyVPCStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt MyVPCStack.Outputs.PublicSubnet2        
        ALBSecurityGroup: !GetAtt SecurityGroupStack.Outputs.WebSG





  Autoscalingstack:    
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${MyBucketName}.s3.us-east-1.amazonaws.com/autoscaling.yml
      Parameters:
        MyKeyName: !Ref MyKeyName
        ImageId: !Ref ImageId
        InstanceType: !Ref InstanceType        
        ALBSG: !GetAtt SecurityGroupStack.Outputs.WebSG
        PublicSubnet1: !GetAtt MyVPCStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt MyVPCStack.Outputs.PublicSubnet2
        EndpointAddr: !GetAtt DatabaseBstack.Outputs.EndpointAddress
        ismaeelTargetGroup: !GetAtt ApplicatonLoadbalancerStack.Outputs.targetgroup



