AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  PublicSubnet1:
    Type: String
  PublicSubnet2:
    Type: String  
  DatabasePrivateIp:
    Type: String
  ImageId:
    Type: String   
  MyKeyName:
    Type: String  
  ALBSG:
    Type: String 
  dbname: 
    Type: String
    Default: wordpress
  dbuserpassword:
    Type: String
    Default: qniwHfNH;1Tl12
  dbusername:
    Type: String
    Default: remotewpuser2
  ismaeelTargetGroup:
    Type: String 
  InstanceType:
    Type: String


Resources:
 ismaeelLaunchConfiguration2:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
        AssociatePublicIpAddress: true
        ImageId: !Ref ImageId
        InstanceType: !Ref InstanceType
        InstanceMonitoring: false
        KeyName: !Ref MyKeyName
        LaunchConfigurationName: ismaeelLaunchConfiguration2    
        SecurityGroups:
          - !Ref ALBSG
        UserData:
            Fn::Base64 : 
              !Sub  |
                #!/bin/bash
                sudo su
                yum install httpd php-mysql -y
                amazon-linux-extras install -y php7.3
                cd /var/www/html
                wget https://wordpress.org/latest.tar.gz
                tar -xzf latest.tar.gz
                cp -r wordpress/* /var/www/html/
                rm -rf wordpress
                rm -rf latest.tar.gz
                chmod -R 755 wp-content
                chown -R apache:apache wp-content
                service httpd start
                chkconfig httpd on
                cd /var/www/html
                cp wp-config-sample.php wp-config.php
                sed -i "s/database_name_here/${dbname}/g" wp-config.php
                 sed -i "s/username_here/${dbusername}/g" wp-config.php
                  sed -i "s/password_here/${dbuserpassword}/g" wp-config.php
                sed -i "s/localhost/${DatabasePrivateIp}/g" wp-config.php


 ismaeelASG2:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: ismaeelASG2
      MinSize: "1"
      MaxSize: "2"
      DesiredCapacity: "2"
      HealthCheckGracePeriod: 100   #The amount of time, in seconds, that Amazon EC2 Auto Scaling waits before checking the health status of an EC2 instance that has come into service.
      TargetGroupARNs: 
        - !Ref ismaeelTargetGroup      
      LaunchConfigurationName: !Ref ismaeelLaunchConfiguration2 
      VPCZoneIdentifier:
        - !Ref PublicSubnet2
        - !Ref PublicSubnet1
      Tags:
        - Key: Name
          Value: ismaeelasg2
          PropagateAtLaunch: true   # Set to true if you want CloudFormation to copy the tag to EC2 instances that are launched as part of the Auto Scaling group.
