AWSTemplateFormatVersion: "2010-09-09"


Parameters:
  DBNamep:
    Default: 
    type: String
  MUser:
    Default: 
    type: String
  MPass:
    Default:  
    type: String
  PrivateSubnet1: 
    type: String
  DBsecurityGroup: 
    type: String




Resources:
  MyDBinstacee:
    Type: AWS::RDS::DBInstance
    properties:
      DBName: !Ref DBNamep
      MasterUsername: !Ref MUser
      MasterPassword: !Ref MPass
      Engine: MySQL
      DBInstanceClass: db.t2.micro
      StorageType: gp2
      PublicAccessible: false
      AllocatedStorage: "20"
      DBSecurityGroups: !Ref 
      DBSubnetGroupName: !Ref
  
  DBSubnetGroupName:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: DBSubnetGroup
      SubnetIds: 
        - !Ref PrivateSubnet1
 
  DBSecurityGroups:
    Type: AWS::RDS::DBSecurityGroupIngressf







 Type: AWS::RDS::DBSecurityGroupIngress
Properties: 
  DBSecurityGroupName: !Ref DBsecurityGroup




